ALL_SEND_PROBE = "[SPACCOM]"
UDP_RECV_PROBE = "[COMMUDP]"
TCP_RECV_PROBE = "[COMMTCP]"
RDB_RECV_PROBE = "[COMMRDB]"

LOCK = 0x1
ULCK = 0x2
TCP_CONN = 0x5
SOCK_CLOS = 0x6
INIT = 0x7

TCP_RECV = 0x3
TCP_SEND = 0x4
UDP_RECV = 0x8
UDP_SEND = 0x9
RESET_NET = 0xA

TCP_COMM_MODE = 104
UDP_COMM_MODE = 105
UDDP_COMM_MODE = 106	# User Defined Data Protocol
SCTP_COMM_MODE = 107
IPPROTO_SCTP = 132
